show databases;
use travelagency;
show tables;
create table airport_list(id int, gmt decimal(4,2), airport_id int, iata_code char(3), city_iata_code char(3), icao_code char(4), country_iso2 char(2), geoname_id int,
lattitude decimal(8,6), longitude decimal(9,6), airport_name varchar(80), country_name varchar(50), phone_number varchar(15), timezone varchar(50));
show tables;
describe airport_list;
truncate table airport_list;
load data local infile "/home/ajiri/project/aviationDataAnalysis/data/raw/airport_list.csv" into table airport_list fields terminated by',' lines terminated by '\n' ignore 1 lines;
select * from airport_list limit 15;
select count(*) from airport_list;
select count(id) from airport_list;
select count(airport_id) from airport_list;
select * from airport_list where airport_id is null;
select count(*) from airport_list where airport_id is null;
select count(id) from airport_list where id = 0;
delete from airport_list where id=0;
select count(distinct(airport_id)) from airport_list;
select count(distinct(id)) from airport_list;
select id from airport_list group by id having count(id) > 1;
select airport_id from airport_list group by airport_id having count(airport_id) > 1;
alter table airport_list add unique (id);
select iata_code from airport_list group by iata_code having count(iata_code) > 1;
select (select iata_code from airport_list group by iata_code having count(iata_code) > 1;) * from airport_list;