version: "3.8"

services:
  postgres:
    image: postgres:17.4   # Use the exact version installed locally
    container_name: postgres_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8.0.41   # Match your installed MySQL version
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aviation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongo:
    image: mongo:8.0.4   # Match your MongoDB version
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  airflow:
    image: apache/airflow:2.9.1   # Match your Airflow version
    container_name: airflow
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
      #sqlite:////home/ajiri/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    restart: always
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init && airflow webserver & airflow scheduler"

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
