
services:

  app:
    build: .
    container_name: aviation_analysis_app_container
    network_mode: "host"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MONGO_HOST: localhost
      MONGO_PORT: 27017

    volumes:
      - ./etl:/app/etl
      - ./tests:/app/tests
      - ./config:/app/config
      - ./data:/app/data
      - ./dags:/app/dags

